import initSoftScroll from './modules/soft-scroll.js';
import initscrollAnimation from './modules/scroll-animation.js';
import initAccordion from './modules/accordion.js';
import initTabNavigation from './modules/tabnav.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdownMenu from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initOperation from './modules/operations.js';
import initFetchAnimais from './modules/fetch-animais.js';
import initFetchBitcoin from './modules/fetch-bitcoin.js';

initSoftScroll();
initscrollAnimation();
initAccordion();
initTabNavigation();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initOperation();
initFetchAnimais();
initFetchBitcoin();
